version: '3'
services:
  shortcake:
    image: shortcake:latest
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile
    restart: "no"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - shortcake:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  shortcake:
