name: delete-docker

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      tag:
        type: string
        required: true
      dockerhub_orgname:
        type: string
        required: true
      github_orgname:
        type: string
        required: true
    secrets:
      dockerhub_username:
        required: true
      # Requires password not token because API currently does not support token
      # dockerhub_token:
      #   required: true
      dockerhub_password:
        required: true
      github_token:
        required: true

jobs:
  delete-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install requests
        run: pip install requests

      - name: "Delete image from Docker Hub"
        shell: python
        run: |
          import requests

          LOGIN_URL = "${DOCKERHUB_API_ADDRESS}/${LOGIN_API_PATH}"
          TAG_URL = (
              "${DOCKERHUB_API_ADDRESS}/"
              "${REPO_API_PATH}/${IMAGE_API_PATH}/${TAG_API_PATH}/"
          )

          dockerhub_jwt_token_req = requests.post(
              LOGIN_URL,
              json={
                  "username": "${{ secrets.dockerhub_username }}",
                  "password": "${{ secrets.dockerhub_username }}",
              },
          )
          dockerhub_jwt_token = dockerhub_jwt_token_req.json()["token"]

          requests.delete(
              TAG_URL,
              headers={"Authorization": f"JWT {dockerhub_token}"},
          )
        env:
          DOCKERHUB_API_ADDRESS: "https://hub.docker.com/v2"
          LOGIN_API_PATH: "users/login"
          REPO_API_PATH: "repositories/${{ inputs.dockerhub_orgname }}"
          IMAGE_API_PATH: "${{ inputs.image_name }}"
          TAG_API_PATH: "tags/${{ inputs.tag }}"

      - name: "Delete image from GitHub Container Registry"
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: ${{ inputs.github_orgname }}
          name: ${{ inputs.image_name }}
          token: ${{ secrets.github_token }}
          tag: ${{ inputs.tag }}
