name: deploy-docker

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      tag:
        type: string
        required: true
      tag_latest:
        type: boolean
        required: false
        default: false
      dockerhub_orgname:
        type: string
        required: true
      dockerhub_username:
        type: string
        required: true
      github_orgname:
        type: string
        required: true
    secrets:
      dockerhub_token:
        required: true
      github_token:
        required: true

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Docker meta"
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ inputs.dockerhub_orgname }}/${{ inputs.image_name }}
            ghcr.io/${{ inputs.github_orgname }}/${{ inputs.image_name }}
          tags: |
            type=raw,${{ inputs.tag }}
          flavor: latest=${{ inputs.tag_latest }}

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      - name: "Log in to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ inputs.github_orgname }}
          password: ${{ secrets.github_token }}

      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          file: build/docker/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
