name: deploy-docker

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      tag_latest:
        type: boolean
        required: false
        default: false

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Docker meta"
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_ORG }}/shortcake
            ghcr.io/${{ github.repository_owner }}/shortcake
          tags: |
            type=raw,${{ inputs.tag }}
          flavor: latest=${{ inputs.tag_latest }}

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: "Log in to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          file: build/docker/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
