name: dev-teardown

on:
  pull_request:
    types: [ converted_to_draft, closed ]

jobs:

  dev-docker-delete:
    # yamllint disable-line rule:line-length
    uses: shortcake-dev/shortcake/.github/workflows/delete-docker.yml@9a8d40d1001eeb6a1f8e2d4c29fc969f3596509a
    with:
      image_name: "shortcake"
      tag: "dev-pr${{ github.event.number }}"
      # TODO: secrets context does not appear to exist here? Luckily this isn't
      #       actually a secret
      # dockerhub_orgname: ${{ secrets.DOCKERHUB_ORG }}
      dockerhub_orgname: shortcakedev
      github_orgname: ${{ github.repository_owner }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      github_token: ${{ secrets.GITHUB_TOKEN }}
