name: dev-teardown

on:
  pull_request:
    types: [ converted_to_draft, closed ]

jobs:

  dev-docker-delete:
    uses: ./.github/workflows/delete-docker.yml
    with:
      image_name: "shortcake"
      tag: "dev-pr${{ github.event.number }}"
      github_orgname: ${{ github.repository_owner }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_orgname: ${{ secrets.DOCKERHUB_ORG }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      ghcr_pat: ${{ secrets.GH_PAT_SHORTCAKE_GHCR_ADMIN }}
