name: dev-deploy

on:
  pull_request:
    types: [ synchronize, reopened, opened, ready_for_review ]

jobs:

  dev-docker-deploy:
    # yamllint disable-line rule:line-length
    uses: shortcake-dev/shortcake/.github/workflows/deploy-docker.yml@034e63df802bed21fd1da45f6741f12b43fc6030
    with:
      image_name: "shortcake"
      tag: "dev-pr${{ github.event.number }}"
      # TODO: secrets context does not appear to exist here? Luckily this isn't
      #       actually a secret
      # dockerhub_orgname: ${{ secrets.DOCKERHUB_ORG }}
      dockerhub_orgname: shortcakedev
      github_orgname: ${{ github.repository_owner }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
