name: dev-deploy

on:
  pull_request:
    types: [ synchronize, reopened, opened, ready_for_review ]

jobs:

  dev-docker-deploy:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      image_name: "shortcake"
      tag: "dev-pr${{ github.event.number }}"
      dockerhub_orgname: ${{ secrets.DOCKERHUB_ORG }}
      github_orgname: ${{ github.repository_owner }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
