name: main-deploy

on:
  push:
    branches: [ main ]

jobs:

  main-docker-deploy:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      image_name: "shortcake"
      tag: "latest"
      github_orgname: ${{ github.repository_owner }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_orgname: ${{ secrets.DOCKERHUB_ORG }}
      dockerhub_token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
